### ISSUE TITLE
Visualization of principal components

### ISSUE THREAD

**Issue by hzzhyj** [GAA-UAM/scikit-fda#199] opened 2020-04-20 21:06 UTC
**Is your feature request related to a problem? Please describe.**
When we have computed the principal components for a certain dataset, it is often helpful to see perturbations of the mean caused by the principal component. However, we currently do not have any method that does that automatically. 

**Describe the solution you'd like**
Create a method in FPCA that creates a list of new FDataBasis or FDataGrid objects. Each object contains the perturbations of one principal component over the mean function, so we can plot the effects of the principal components.

**Alternate solution**
Instead of creating a list with the perturbations of all principal components, maybe we can pass an index of one chosen principal component. We can also implement both methods and have one call another.

**Comment by EPauthenet** [comment] 2020-05-19 14:35
Hello @hzzhyj, 
we have coded this in as part of a repository ([fda.oce](https://github.com/EPauthenet/fda_oce_python)) using fpca to classify hydrographic profiles. 
We plot the perturbation of the mean property profile (temperature,salinity,...) caused by each principal components. The plotting function is called [eigenf_plot](https://github.com/EPauthenet/fda_oce_python/blob/master/fda_oce_python.py).
This repository was initially written in R, there is more examples on the R version :[ fda.oce](https://github.com/EPauthenet/fda.oce).
Feel free to reuse any of this material if that helps!
Best,
Etienne

**Comment by vnmabus** [comment] 2020-06-17 08:50
Closed by #209 .

**Closed** 2020-06-17 08:50 UTC
Labels: enhancement
